global:
  scrape_interval: 10s
  evaluation_interval: 10s
  scrape_timeout: 10s

rule_files:
  - /etc/prometheus/alert.yml

scrape_configs:
  - job_name: "node"
    static_configs:
      - targets: ["chat:5000"]
  - job_name: "db"
    static_configs:
      - targets: ["db-exporter:9216"]
